#si "comic". "pop-art", "watercolor"
lista_estilos = ["impresionist", "art nouveau", "japanese-style", "japanese-animation", "watercolor", "comic-book", "comic", "picture", "pop-art", "painting", "watercolor", "anime", "watercolor", "comic", "watercolor", "dibujo", "manga", "pop-art", "lineart", "manga"]
lista_subjects = ["Aquaman", 
                  "The Boys John / Homelander", 
                  "", 
                  "Peacemaker", 
                  "", 
                  "Birdman",
                  "",
                  "Bruce Wayne", 
                  "", 
                  "Dr.Manhattan",
                  "",
                  "Green Lantern", 
                  "Human Torch",
                  "",
                  "Logan Wolverine",
                  "",
                  "Mr. Fantastic",
                  "", 
                  "Shazam", 
                  "", 
                  "", 
                  "X-Men Colossus" 
                  "",
                  "Quicksilver" 
                  "",
                  "Magneto", 
                  "", 
                  "Hawkeye", 
                  "", 
                  "Dr.Strange", 
                  "", 
                  "Deathshot", 
                  "", 
                  "StarLord", 
                  "", 
                  "Superman", 
                  "", 
                  "Clark Kent",
                  "", 
                  "Tony Stark", 
                  "", 
                  "Spiderman", 
                  "", 
                  "Peter Parker",
                  "",
                  "Silver Surfer",                  
                  "", 
                  "Flash", 
                  "", 
                  "Robin",
                  "",
                  "Watchmen",
                  "",
                  "Warlock", 
                  "",
                  "Wade Wilson Deadpool", 
                  "X-Men", 
                  "", 
                  "X-men Cyclops"
                  ]
#salieron: "", "image" e "imagen"
#salieron: "thor", "punisher", "Captain-America"